"""Add AIProvider and update AIModel

Revision ID: 0d1fce1f91b3
Revises: c1d41684f1a8
Create Date: 2026-06-21 15:30:25.201194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1fce1f91b3'
down_revision = 'c1d41684f1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_providers_slug'), ['slug'], unique=True)

    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_ai_models_provider_id'), ['provider_id'], unique=False)
        batch_op.create_foreign_key(None, 'ai_providers', ['provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ai_models_provider_id'))
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_providers_slug'))

    op.drop_table('ai_providers')
    # ### end Alembic commands ###
