"""add lessor fields and reminder to contract template

Revision ID: 568c52d70c28
Revises: 7ba34b255577
Create Date: 2026-06-13 02:56:04.844591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568c52d70c28'
down_revision = '7ba34b255577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lessor_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('lessor_id_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lessor_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lessor_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminder_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.drop_column('reminder_message')
        batch_op.drop_column('lessor_address')
        batch_op.drop_column('lessor_phone')
        batch_op.drop_column('lessor_id_number')
        batch_op.drop_column('lessor_name')

    # ### end Alembic commands ###
