"""change api_key to text

Revision ID: 5f9a729a29c2
Revises: e70263019f70
Create Date: 2026-06-26 16:15:24.558863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9a729a29c2'
down_revision = 'e70263019f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.alter_column('image_api_key',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('image_api_secret',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('voice_api_key',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('call_api_key',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('call_api_secret',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('tenant_integrations', schema=None) as batch_op:
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_integrations', schema=None) as batch_op:
        batch_op.alter_column('api_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.alter_column('call_api_secret',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('call_api_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('voice_api_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('image_api_secret',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('image_api_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.alter_column('api_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
