"""init

Revision ID: 69e5996fe472
Revises: 
Create Date: 2026-05-01 03:33:42.198127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e5996fe472'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_path', sa.String(length=255), nullable=True),
    sa.Column('intents', sa.JSON(), nullable=True),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_code'), ['code'], unique=True)

    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_per_message', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_per_message', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('quality_tier', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_models_provider'), ['provider'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('max_chats_per_month', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_code'), ['code'], unique=True)

    op.create_table('service_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_pricing_service_key'), ['service_key'], unique=True)

    op.create_table('super_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('super_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_super_admins_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_super_admins_username'), ['username'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('owner_full_name', sa.String(length=200), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('owner_phone', sa.String(length=30), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_owner_email'), ['owner_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_type'), ['actor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bot_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=30), nullable=True),
    sa.Column('bot_name', sa.String(length=100), nullable=True),
    sa.Column('agent_gender', sa.String(length=10), nullable=False),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('blocked_topics', sa.Text(), nullable=True),
    sa.Column('image_provider', sa.String(length=30), nullable=True),
    sa.Column('image_api_key', sa.String(length=300), nullable=True),
    sa.Column('image_api_secret', sa.String(length=300), nullable=True),
    sa.Column('voice_provider', sa.String(length=30), nullable=True),
    sa.Column('voice_api_key', sa.String(length=300), nullable=True),
    sa.Column('ai_provider', sa.String(length=30), nullable=True),
    sa.Column('ai_api_key', sa.String(length=500), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('call_provider', sa.String(length=30), nullable=True),
    sa.Column('call_api_key', sa.String(length=300), nullable=True),
    sa.Column('call_api_secret', sa.String(length=300), nullable=True),
    sa.Column('call_phone_number', sa.String(length=30), nullable=True),
    sa.Column('call_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('call_is_active', sa.Boolean(), nullable=True),
    sa.Column('call_voice', sa.String(length=30), nullable=True),
    sa.Column('call_greeting', sa.Text(), nullable=True),
    sa.Column('knowledge_base', sa.Text(), nullable=True),
    sa.Column('knowledge_files_count', sa.Integer(), nullable=True),
    sa.Column('knowledge_last_updated', sa.DateTime(), nullable=True),
    sa.Column('auto_learn_enabled', sa.Boolean(), nullable=True),
    sa.Column('learned_replies_count', sa.Integer(), nullable=True),
    sa.Column('semantic_intent_enabled', sa.Boolean(), nullable=False),
    sa.Column('semantic_threshold', sa.Float(), nullable=False),
    sa.Column('whatsapp_auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_configs_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('map_link', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('complaints_email', sa.String(length=255), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('chat_visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('visitor_token', sa.String(length=64), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_code_hash', sa.String(length=64), nullable=True),
    sa.Column('verification_salt', sa.String(length=32), nullable=True),
    sa.Column('verification_expires', sa.DateTime(), nullable=True),
    sa.Column('verification_attempts', sa.Integer(), nullable=True),
    sa.Column('verification_locked_until', sa.DateTime(), nullable=True),
    sa.Column('verification_code', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_tenant_visitor_email')
    )
    with op.batch_alter_table('chat_visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_visitors_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_visitors_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_visitors_visitor_token'), ['visitor_token'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('visitor_name', sa.String(length=200), nullable=True),
    sa.Column('visitor_phone', sa.String(length=30), nullable=True),
    sa.Column('visitor_email', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('custom_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('inquiry_id', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_replies_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_replies_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_replies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('hotel_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotel_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotel_services_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('api_secret', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('phone_number_id', sa.String(length=50), nullable=True),
    sa.Column('waba_id', sa.String(length=50), nullable=True),
    sa.Column('webhook_verify_token', sa.String(length=100), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('payment_currency', sa.String(length=10), nullable=True),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('messages_received', sa.Integer(), nullable=True),
    sa.Column('payments_count', sa.Integer(), nullable=True),
    sa.Column('payments_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'service_type', name='uq_tenant_service')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('restaurant_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_categories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('restaurant_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('min_order', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('delivery_areas', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_services_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('chats_used_this_month', sa.Integer(), nullable=False),
    sa.Column('ai_calls_this_month', sa.Integer(), nullable=False),
    sa.Column('usage_reset_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('tenant_deletion_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_deletion_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_deletion_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_deletion_codes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_tenant_username')
    )
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_users_username'), ['username'], unique=False)

    op.create_table('tenant_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_topped_up', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('low_balance_threshold', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('auto_stop_threshold', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('low_balance_alerted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_wallets_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('wallet_topups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('payment_ref', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_topups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_topups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_topups_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('hotel_floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'number', name='uq_branch_floor')
    )
    with op.batch_alter_table('hotel_floors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotel_floors_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_floors_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.String(length=64), nullable=True),
    sa.Column('visitor_name', sa.String(length=200), nullable=True),
    sa.Column('visitor_phone', sa.String(length=30), nullable=True),
    sa.Column('visitor_email', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('inquiry_kind', sa.String(length=20), nullable=False),
    sa.Column('complaint_category', sa.String(length=40), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_to', sa.String(length=255), nullable=True),
    sa.Column('visitor_notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiries_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_complaint_category'), ['complaint_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_inquiry_kind'), ['inquiry_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('message_usage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('ai_model_id', sa.Integer(), nullable=True),
    sa.Column('price_charged', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_actual', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_usage_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_usage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_type'), ['sender_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('restaurant_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('prep_time_min', sa.Integer(), nullable=True),
    sa.Column('is_spicy', sa.Boolean(), nullable=True),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['restaurant_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_items_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_items_is_available'), ['is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('hotel_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.String(length=30), nullable=False),
    sa.Column('unit_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bedrooms_count', sa.Integer(), nullable=True),
    sa.Column('living_rooms', sa.Integer(), nullable=True),
    sa.Column('halls', sa.Integer(), nullable=True),
    sa.Column('bathrooms_count', sa.Integer(), nullable=True),
    sa.Column('kitchens', sa.Integer(), nullable=True),
    sa.Column('extra_rooms', sa.String(length=200), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=True),
    sa.Column('daily_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yearly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability_type', sa.String(length=20), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('image_360_link', sa.String(length=500), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['hotel_floors.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'unit_number', name='uq_branch_unit')
    )
    with op.batch_alter_table('hotel_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotel_units_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_units_is_available'), ['is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_units_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_units_unit_type'), ['unit_type'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('booking_type', sa.String(length=30), nullable=False),
    sa.Column('booking_number', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=30), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('checkin_date', sa.Date(), nullable=True),
    sa.Column('checkout_date', sa.Date(), nullable=True),
    sa.Column('reservation_date', sa.Date(), nullable=True),
    sa.Column('reservation_time', sa.String(length=10), nullable=True),
    sa.Column('guests_count', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('requested_unit_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.String(length=64), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['hotel_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_number')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_type'), ['booking_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_created_at'))
        batch_op.drop_index(batch_op.f('ix_bookings_branch_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_type'))

    op.drop_table('bookings')
    with op.batch_alter_table('hotel_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotel_units_unit_type'))
        batch_op.drop_index(batch_op.f('ix_hotel_units_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_hotel_units_is_available'))
        batch_op.drop_index(batch_op.f('ix_hotel_units_branch_id'))

    op.drop_table('hotel_units')
    with op.batch_alter_table('restaurant_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_restaurant_items_is_available'))
        batch_op.drop_index(batch_op.f('ix_restaurant_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_restaurant_items_branch_id'))

    op.drop_table('restaurant_items')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_type'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('message_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_usage_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_message_usage_service_type'))
        batch_op.drop_index(batch_op.f('ix_message_usage_created_at'))

    op.drop_table('message_usage')
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquiries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inquiries_status'))
        batch_op.drop_index(batch_op.f('ix_inquiries_inquiry_kind'))
        batch_op.drop_index(batch_op.f('ix_inquiries_created_at'))
        batch_op.drop_index(batch_op.f('ix_inquiries_complaint_category'))
        batch_op.drop_index(batch_op.f('ix_inquiries_branch_id'))

    op.drop_table('inquiries')
    with op.batch_alter_table('hotel_floors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotel_floors_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_hotel_floors_branch_id'))

    op.drop_table('hotel_floors')
    with op.batch_alter_table('wallet_topups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_topups_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_topups_created_at'))

    op.drop_table('wallet_topups')
    with op.batch_alter_table('tenant_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_wallets_tenant_id'))

    op.drop_table('tenant_wallets')
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_users_username'))
        batch_op.drop_index(batch_op.f('ix_tenant_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_users_email'))

    op.drop_table('tenant_users')
    with op.batch_alter_table('tenant_deletion_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_deletion_codes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_deletion_codes_expires_at'))

    op.drop_table('tenant_deletion_codes')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('restaurant_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_services_tenant_id'))

    op.drop_table('restaurant_services')
    with op.batch_alter_table('restaurant_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_categories_tenant_id'))

    op.drop_table('restaurant_categories')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_integrations_service_type'))

    op.drop_table('integrations')
    with op.batch_alter_table('hotel_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotel_services_tenant_id'))

    op.drop_table('hotel_services')
    with op.batch_alter_table('custom_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_replies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_custom_replies_source'))
        batch_op.drop_index(batch_op.f('ix_custom_replies_is_active'))

    op.drop_table('custom_replies')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_channel'))

    op.drop_table('conversations')
    with op.batch_alter_table('chat_visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_visitors_visitor_token'))
        batch_op.drop_index(batch_op.f('ix_chat_visitors_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_visitors_email'))

    op.drop_table('chat_visitors')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_tenant_id'))

    op.drop_table('branches')
    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_configs_tenant_id'))

    op.drop_table('bot_configs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_status'))
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))
        batch_op.drop_index(batch_op.f('ix_tenants_plan_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_owner_email'))
        batch_op.drop_index(batch_op.f('ix_tenants_activity_id'))

    op.drop_table('tenants')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.drop_index(batch_op.f('ix_system_settings_category'))

    op.drop_table('system_settings')
    with op.batch_alter_table('super_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_super_admins_username'))
        batch_op.drop_index(batch_op.f('ix_super_admins_email'))

    op.drop_table('super_admins')
    with op.batch_alter_table('service_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_pricing_service_key'))

    op.drop_table('service_pricing')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_code'))

    op.drop_table('plans')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_subject_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_models_provider'))

    op.drop_table('ai_models')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_code'))

    op.drop_table('activities')
    # ### end Alembic commands ###
