"""Add missing fields

Revision ID: 6e727ddc7494
Revises: c38cbfda4508
Create Date: 2026-06-17 02:34:19.152908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e727ddc7494'
down_revision = 'c38cbfda4508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('monthly_usage_limit', sa.Integer(), nullable=False),
    sa.Column('max_conversations', sa.Integer(), nullable=False),
    sa.Column('max_voice_calls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('integration_name', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_employees', sa.Integer(), nullable=False),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('max_whatsapp_msgs', sa.Integer(), nullable=False),
    sa.Column('max_sms', sa.Integer(), nullable=False),
    sa.Column('max_emails', sa.Integer(), nullable=False),
    sa.Column('max_push_notifications', sa.Integer(), nullable=False),
    sa.Column('max_contracts_per_month', sa.Integer(), nullable=False),
    sa.Column('storage_limit_gb', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('plan_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('stripe_price_id_monthly', sa.String(length=100), nullable=True),
    sa.Column('stripe_price_id_yearly', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('is_popular', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('badge_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('badge_text', sa.String(length=50), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('price_yearly')
        batch_op.drop_column('max_branches')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('max_users')
        batch_op.drop_column('features')
        batch_op.drop_column('currency')
        batch_op.drop_column('is_active')
        batch_op.drop_column('price_monthly')
        batch_op.drop_column('max_chats_per_month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_chats_per_month', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price_monthly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_branches', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price_yearly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('badge_text')
        batch_op.drop_column('badge_color')
        batch_op.drop_column('is_popular')
        batch_op.drop_column('status')
        batch_op.drop_column('description_en')
        batch_op.drop_column('description_ar')

    op.drop_table('plan_pricing')
    op.drop_table('plan_permissions')
    op.drop_table('plan_modules')
    op.drop_table('plan_limits')
    op.drop_table('plan_integrations')
    op.drop_table('plan_agents')
    # ### end Alembic commands ###
