"""add support_tickets

Revision ID: 7020d050930e
Revises: 5f9a729a29c2
Create Date: 2026-06-28 02:17:51.867399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7020d050930e'
down_revision = '5f9a729a29c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('signature_ip', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_contracts_signature_token'), ['signature_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_signature_token'))
        batch_op.drop_column('signature_ip')
        batch_op.drop_column('signature_token')

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))

    op.drop_table('support_tickets')
    # ### end Alembic commands ###
