"""Add unit status

Revision ID: 7ba34b255577
Revises: 69e5996fe472
Create Date: 2026-06-13 02:20:53.869458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ba34b255577'
down_revision = '69e5996fe472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_templates_provider'), ['provider'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_unit_id'), ['unit_id'], unique=False)

    with op.batch_alter_table('hotel_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_hotel_units_status'), ['status'], unique=False)

    with op.batch_alter_table('restaurant_items', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_items', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('hotel_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotel_units_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_unit_id'))

    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_templates_provider'))

    # ### end Alembic commands ###
