"""add agent profiles and update ai settings

Revision ID: e70263019f70
Revises: 0d1fce1f91b3
Create Date: 2026-06-26 01:37:03.681162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70263019f70'
down_revision = '0d1fce1f91b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('tone', sa.String(length=30), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_type', name='uix_tenant_agent_type')
    )
    with op.batch_alter_table('agent_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_profiles_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_profiles_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.drop_column('ai_api_key')
        batch_op.drop_column('ai_provider')
        batch_op.drop_column('ai_model')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_unlimited_ai', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('has_unlimited_ai')

    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_provider', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('api_key')

    with op.batch_alter_table('agent_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_profiles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_profiles_agent_type'))

    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
