"""Add iCal sync fields to Unit

Revision ID: e75398ead686
Revises: 568c52d70c28
Create Date: 2026-06-15 01:03:50.523124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75398ead686'
down_revision = '568c52d70c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ical_import_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('ical_export_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['ical_export_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ical_export_token')
        batch_op.drop_column('ical_import_url')

    # ### end Alembic commands ###
